name: Build

on:
  release:
    types: [published]
  push:
    branches:    
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  pull_request:
    branches:
      - 'main'
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  vosk-server-cpu:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for vosk-server CPU
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/double16/kaldi-vosk-server
          tags: |
            type=semver,pattern={{version}}
            ${{ github.ref == 'refs/heads/master' && 'type=raw,value=latest' || '' }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push vosk-server CPU
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.kaldi-vosk-server
          build-args: |
            KALDI_MKL=0
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true

  vosk-server-cpu-kinds:
    runs-on: ubuntu-24.04
    needs: [vosk-server-cpu]
    strategy:
      matrix:
        kind: ["en", "en-spk", "es"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for vosk-server CPU
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/double16/kaldi-${{ matrix.kind }}
          tags: |
            type=semver,pattern={{version}}
            ${{ github.ref == 'refs/heads/master' && 'type=raw,value=latest' || '' }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push vosk-server CPU
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.kaldi-${{ matrix.kind }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true

  vosk-server-gpu:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for vosk-server CPU
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/double16/kaldi-vosk-server-gpu
          tags: |
            type=semver,pattern={{version}}
            ${{ github.ref == 'refs/heads/master' && 'type=raw,value=latest' || '' }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push vosk-server CPU
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.kaldi-vosk-server-gpu
          build-args: |
            KALDI_MKL=0
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true

  vosk-server-gpu-kinds:
    runs-on: ubuntu-24.04
    needs: [vosk-server-gpu]
    strategy:
      matrix:
        kind: ["en"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for vosk-server CPU
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/double16/kaldi-${{ matrix.kind }}-gpu
          tags: |
            type=semver,pattern={{version}}
            ${{ github.ref == 'refs/heads/master' && 'type=raw,value=latest' || '' }}
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index

      - name: Build and push vosk-server CPU
        uses: docker/build-push-action@v6
        with:
          context: docker
          file: docker/Dockerfile.kaldi-${{ matrix.kind }}-gpu
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,oci-mediatypes=true,compression=zstd,compression-level=3,force-compression=true
